module.exports = (req, res) => {
  const keywords = [
  "english translator",
  "spanish translator",
  "french translator",
  "german translator",
  "chinese translator",
  "japanese translator",
  "arabic translator",
  "portuguese translator",
  "russian translator",
  "korean translator",
  "italian translator",
  "dutch translator",
  "greek translator",
  "maltese translator",
  "luxembourgish translator",
  "swedish translator",
  "danish translator",
  "norwegian translator",
  "finnish translator",
  "icelandic translator",
  "polish translator",
  "czech translator",
  "slovak translator",
  "hungarian translator",
  "romanian translator",
  "bulgarian translator",
  "serbian translator",
  "croatian translator",
  "slovenian translator",
  "bosnian translator",
  "macedonian translator",
  "albanian translator",
  "estonian translator",
  "latvian translator",
  "lithuanian translator",
  "ukrainian translator",
  "georgian translator",
  "armenian translator",
  "azerbaijani translator",
  "catalan translator",
  "basque translator",
  "galician translator",
  "welsh translator",
  "irish translator",
  "hebrew translator",
  "persian translator",
  "turkish translator",
  "kurdish translator",
  "pashto translator",
  "yiddish translator",
  "kazakh translator",
  "uzbek translator",
  "kyrgyz translator",
  "tajik translator",
  "turkmen translator",
  "hindi translator",
  "bengali translator",
  "urdu translator",
  "punjabi translator",
  "tamil translator",
  "telugu translator",
  "marathi translator",
  "gujarati translator",
  "kannada translator",
  "malayalam translator",
  "odia translator",
  "nepali translator",
  "sinhala translator",
  "vietnamese translator",
  "thai translator",
  "indonesian translator",
  "malay translator",
  "tagalog translator",
  "khmer translator",
  "lao translator",
  "burmese translator",
  "cantonese translator",
  "mongolian translator",
  "swahili translator",
  "amharic translator",
  "hausa translator",
  "yoruba translator",
  "zulu translator",
  "afrikaans translator",
  "somali translator",
  "english interpreter",
  "spanish interpreter",
  "french interpreter",
  "german interpreter",
  "chinese interpreter",
  "japanese interpreter",
  "arabic interpreter",
  "portuguese interpreter",
  "russian interpreter",
  "korean interpreter",
  "italian interpreter",
  "dutch interpreter",
  "greek interpreter",
  "swedish interpreter",
  "danish interpreter",
  "norwegian interpreter",
  "finnish interpreter",
  "polish interpreter",
  "czech interpreter",
  "slovak interpreter",
  "hungarian interpreter",
  "romanian interpreter",
  "bulgarian interpreter",
  "serbian interpreter",
  "croatian interpreter",
  "slovenian interpreter",
  "albanian interpreter",
  "estonian interpreter",
  "latvian interpreter",
  "lithuanian interpreter",
  "ukrainian interpreter",
  "georgian interpreter",
  "armenian interpreter",
  "azerbaijani interpreter",
  "hebrew interpreter",
  "persian interpreter",
  "turkish interpreter",
  "kurdish interpreter",
  "pashto interpreter",
  "hindi interpreter",
  "bengali interpreter",
  "urdu interpreter",
  "punjabi interpreter",
  "tamil interpreter",
  "telugu interpreter",
  "vietnamese interpreter",
  "thai interpreter",
  "indonesian interpreter",
  "malay interpreter",
  "tagalog interpreter",
  "khmer interpreter",
  "burmese interpreter",
  "cantonese interpreter",
  "swahili interpreter",
  "amharic interpreter",
  "somali interpreter",
  "looking for translator",
  "looking for interpreter",
  "hiring translator",
  "hiring interpreter",
  "need translator",
  "need interpreter",
  "linguist",
  "localization",
  "localization manager",
  "localization engineer",
  "localization tester",
  "lqa",
  "proofreader",
  "editor",
  "copy editor",
  "revisor",
  "reviewer",
  "subtitler",
  "captioner",
  "transcriber",
  "voiceover",
  "dubbing",
  "post editor",
  "mtpe",
  "transcreator",
  "terminologist",
  "lexicographer",
  "translation manager",
  "language manager",
  "language specialist",
  "conference interpreter",
  "court interpreter",
  "legal interpreter",
  "medical interpreter",
  "simultaneous interpreter",
  "consecutive interpreter",
  "sign language interpreter",
  "asl interpreter",
  "technical translator",
  "legal translator",
  "medical translator",
  "literary translator",
  "certified translator",
  "sworn translator",
  "game localization",
  "software localization",
  "internationalization",
  "i18n",
  "multilingual copywriter",
  "bilingual",
  "nlp linguist",
  "data annotator"
  ];

  const keyword = `"${keywords[Math.floor(Math.random() * keywords.length)]}"`;

  res.status(200).json({ keyword });
};
