module.exports = (req, res) => {
  const keywords = [
    "french translator",
    "chinese translator",
    "japanese translator",
    "arabic translator",
    "portuguese translator",
    "italian translator",
    "turkish translator",
    "korean translator",
    "hindi translator",
    "polish translator",
    "dutch translator",
    "swedish translator",
    "norwegian translator",
    "danish translator",
    "finnish translator",
    "czech translator",
    "greek translator",
    "ukrainian translator",
    "english interpreter",
    "spanish interpreter",
    "russian interpreter",
    "german interpreter",
    "french interpreter",
    "chinese interpreter",
    "japanese interpreter",
    "arabic interpreter",
    "portuguese interpreter",
    "italian interpreter",
    "turkish interpreter",
    "korean interpreter",
    "hindi interpreter",
    "polish interpreter",
    "dutch interpreter",
    "swedish interpreter",
    "norwegian interpreter",
    "danish interpreter",
    "finnish interpreter",
    "czech interpreter",
    "greek interpreter",
    "ukrainian interpreter",
        "editor",
    "proofreader",
    "linguist",
    "copywriter",
    "content writer",
    "content specialist",
    "content strategist",
    "localization specialist",
    "transcreator",
    "ux writer",
    "technical writer",
    "seo writer",
    "scriptwriter",
    "email marketing specialist",
    "qa tester",
    "mtpe",
    "subtitle creator",
    "graphic designer",
    "ui/ux designer",
    "web designer",
    "product designer",
    "brand designer",
    "illustrator",
    "motion designer",
    "3d designer",
    "video editor",
    "photographer",
    "videographer",
    "web developer",
    "frontend developer",
    "backend developer",
    "full stack developer",
    "mobile developer",
    "software engineer",
    "devops engineer",
    "data engineer",
    "qa engineer",
    "data analyst",
    "data scientist",
    "digital marketer",
    "social media manager",
    "seo specialist",
    "ppc specialist",
    "email marketer",
    "growth marketer",
    "marketing strategist",
    "sales consultant",
    "business consultant",
    "management consultant",
    "strategy consultant",
    "financial consultant",
    "hr consultant",
    "project manager",
    "product manager",
    "scrum master",
    "business analyst",
    "virtual assistant",
    "customer support specialist",
    "bookkeeper",
    "accountant",
    "legal consultant",
    "voice over artist",
    "data specialist"
  ];

  const keyword = `"${keywords[Math.floor(Math.random() * keywords.length)]}"`;

  res.status(200).json({ keyword });
};
